### PR TITLE
Add URL check

### PR DESCRIPTION
**Pull request by gizzmojr**
UI doesn't show if wrong site info provided.

Noticed if the hard-coded or site parameter was wrong, the interface doesn't show failure.

### CODE REVIEW

**Comment by leif81** [comment]
Cool that's a good idea.

I'm wondering if we can do a similar sanity check in `loadProductsList` instead of doing an extra rest call just for the site?

**Comment by gizzmojr** [comment]
Funny you mention that, I tried to make an elegant way to return out of the loadParams function if checkURL returned false, but the all async XMLHttprequest's really got me writing dirty code. I didn't want to do nested functions with callbacks, the internet says that's bad coding.

**Comment by leif81** [comment]
I mean can we do the `if (response == "")` inside the existing `loadProductsList` REST call instead of needing the `checkURL` query? It'd be one less REST call we need to make.

~~Side note, for some reason I'm not seeing the `alert` when I supply a bad URL.~~

**Comment by leif81** [comment]
I'll go ahead and merge this and do the refactoring after.

**Pull request merged**
