### PR TITLE
Edit bug title

### PR DESCRIPTION
**Pull request by gizzmojr**
Edit the summary of the bug when edit modal is popped up. 

Inspired by Google Calendar

Also re-ordered the modal header so it's closer to Github

### CODE REVIEW

**Comment by leif81** [comment]
Cool, being able to edit the bug summary is useful.

It's made me think though, maybe we should move the bug title into a Summary field above Description, like the new bug modal.

**Comment by gizzmojr** [comment]
Maybe, on my radar is some stylizing I'd like to do once the modal-comment branch is done. I could take a look then, or if you want to do it go for it.

**Comment by leif81** [comment]
I added a commit to the PR. It totally butchers your work, but this is the alternative I thought would be worth trying.

**Comment by gizzmojr** [comment]
Is it you have a preference for continuity with the rest of the modal? Your original modal header design I really liked, just wanted to edit the title. 

Now the bug.id just hangs out in this big block of whitespace. Seems odd'ish.

**Comment by leif81** [comment]
Ya hmm, is there a third option we could try?

**Comment by gizzmojr** [comment]
I instinctively go to Trello to compare, cause that's my goto for personal kanban. And it's just like how we had it. 
That said, I don't plan to copy everyone else's design but does seem like a good solution without adding more elements in the popup.

**Comment by leif81** [comment]
Ok, lets revert my commit.

I took a look at Trello, one thing I like that they do is change the mouse cursor when hovering the title. Can we do that?

**Comment by gizzmojr** [comment]
Sure! Well spotted, I'm liking more then to making the background colour change.

**Comment by gizzmojr** [comment]
Rebased

I don't have anything else to commit

**Comment by leif81** [comment]
Thanks @gizzmojr . Sorry for the delay. 🐿

**Pull request merged**
