### PR TITLE
No html

### PR DESCRIPTION
**Pull request by leif81**
For issue #38 .

Ok the static HTML in `index.html` has been refactored into javascript. There's just one `div` in the `body` that the board attaches itself too. This was fairly tedious process. But it's done. 😳 😰 😔 😣  I actually prefer it this way now. 😄 I really like setting up the event listeners at the same time as the dom elements. Logically those things are in the same place now which is handy instead of leftovers at the bottom of the js.

@gizzmojr can you take a look and try it out before it's merged? This involved refactoring the whole nav area and the new bug modal. So mostly I'm worried about anything funky in those parts. From my initial smoke testing it seems good though. The only thing I didn't port over was showing the hidden defaults in the modal.

### CODE REVIEW

**Comment by leif81** [comment]
Oh one thing worth noticing is that the whole new bug modal gets re-created on show and removed on hide. So the logic related to clearing the fields was skipped.

**Comment by leif81** [comment]
Just noticed that the last of the three commits caused the column scrolling to break. Should be easy fix.

**Comment by gizzmojr** [comment]
A couple of things;
1. Getting `bzkanban.js:736 Uncaught TypeError: Cannot read property 'appendChild' of null` but it takes quite a few refreshes to get it to kick. (not signed in)
2. After logging in, Drag-n-Drop doesn't show drop targets. After I hit refresh, works fine.

**Comment by leif81** [comment]
Ok think I've fixed those two cases. Plus smoothed out a couple other things.

If you don't mind giving it another try before I merge that'd be cool.

**Comment by leif81** [comment]
Think it's in pretty good shape now so merging.

**Pull request merged**
